### ISSUE TITLE
Add a command to generate a launch script for the image

### ISSUE THREAD

**Issue by demarey** [axlgithub/CommandLineLauncher#1]
The goal is to have an esay way to run the image with a specified configuration.
If the image has many configurations, we could add a --config option to select another configuration

**Comment by Bajger** [comment]
@demarey : Can this be closed? It was moved to done, but I don't see relevant PR.

**Comment by demarey** [comment]
yes, you can see the implementation in this PR: https://github.com/PharoLauncherCmdLine/CommandLineLauncher/pull/17/commits
