### ISSUE TITLE
Extend CI to run shell unit tests testing CLI commands

### ISSUE THREAD

**Issue by Bajger** [axlgithub/CommandLineLauncher#20]
**Describe the request**
CI setup currently run Sunit tests executed in Pharo. For CLI testing purposes, we want to run CI also tests that are bash specific and testing CLI Pharo Launcher commands.

**Expected behavior**  
CI runs bash unit tests specific to CLI of Pharo Launcher and reports potential issues as result of build process.  

**Expected development cost**
- implement new sh function in `build.sh` script called e.g.: `runBashPharoLauncherCLITests()` that would implement something like:
```
#!/bin/bash
set -e
for f in test*.sh; do
  bash "$f"
done
```
- modify `run_tests()` function in `build.sh` to run newly created function (in previous step)

**Opened questions**
- how sh unit test produce output? Is there something like `--junit-xml-output` option?
- where are test artefacts (xml with results) produced?
- Can we make sh unit tests running also on Windows platform?

**Comment by demarey** [comment]
CLI is only working on Linux / OS X. There is no support for Windows. So, testing on Windows is not a concern.
I don't think there is an XML output available. There is only the console feedback. Maybe we could just rely on the script exit code to fail or not the build.

**Comment by Bajger** [comment]
I was testing CLI even on Windows previously (CLAP works under Windows as well). So this was a reason why I was asking.

**Comment by demarey** [comment]
The interaction for Windows CLI (CMD) is really poor in Pharo. We took the decision to do not invest time on supporting a CLI version on Windows. That said, with WLS, current implementation works well. So there is a solution on Windows but is not native. If you are interested in a native support, we will welcome PR happily.

**Comment by Bajger** [comment]
Hi Christophe, I'm really not aware of any blocker issues using CLAP on Windows (but I admit I tried for sample commands). I did also bat file as shortcut in my original repo tu run (headless) launcher using CLAP with supplemental parameters as seen at: https://github.com/Bajger/PharoLauncher-cli/blob/main/script/pharoLauncher.bat
What will definetely won't work is using LibC that invoke shell commands like `ps`. I guess there can be platform specific code that provide batch equivalent (e.g.: instead using `kill` there can be batch like version `taskkill`). Is this adoption what you mean by native support?

**Comment by demarey** [comment]
Yes, the pending PR is linux specific but an implementation using Windows library is possible. Maybe current version of PharoLauncher CLI is working but it has not be tested at all. Could you give feedback from this side? Is everything working on Windows?

**Comment by Bajger** [comment]
Findings so far: 100% test cases passing (package PharoLauncher-CLI-Tests) on P8 64bit stable, OS Name: Microsoft Windows 10 Home, OS Version: 10.0.19042 N/A Build 19042
Tested with Project baseline:
```
Metacello new
	repository: 'github://PharoLauncherCmdLine/CommandLineLauncher:dev/src';
	baseline: 'PharoLauncher';
	load
```

**Comment by demarey** [comment]
> Findings so far: 100% test cases passing (package PharoLauncher-CLI-Tests) on P8 64bit stable, OS Name: Microsoft Windows 10 Home, OS Version: 10.0.19042 N/A Build 19042 Tested with Project baseline:
> 
> ```
> Metacello new
> 	repository: 'github://PharoLauncherCmdLine/CommandLineLauncher:dev/src';
> 	baseline: 'PharoLauncher';
> 	load
> ```

yes, I expected this result. Where, I'm less confident is the use of PL CLI on command line: is the output of commands correct?

**Comment by Bajger** [comment]
Oh, I didn't look what unit tests are doing exactly, but from your comment it seems it doesn't really test expected console output? I would assume, I can run "same commands" from console that are invoked in unit tests of PharoLauncher-CLI package. But problem would be environment preparation (mock objects) in setUp of each unit tests (this cannot be easily achieved in cmd-line I suppose). Or maybe just call content of test*.sh files using Windows cmd-line would be enough?

**Comment by demarey** [comment]
In order to test properly PL CLI on Windows, we would need some functional tests. Commands have their unit tests, so it is ok. What is missing is to test the interaction with Windows CMD, especially getting output of commands once invoked. So if we have a few tests to ensure command input / output (with some special cases with non ASCII characters to test the encoding) is ok, it should be enough to validate Windows native support
