### ISSUE TITLE
Shell unit test for kill all processes failed

### ISSUE THREAD

**Issue by Bajger** [axlgithub/CommandLineLauncher#22]
**Describe the bug**
Shell unit test with running `image kill -all` command failed.

**To Reproduce**
1. Go to `test` directory
2. run `testImageCommands.sh`
3.  See error:
```
ASSERT:
shunit2:ERROR testLauncherKillAllCommandWithOneImageLaunchedShouldKillAll() returned non-zero return code.
testLauncherKillCommandWithOneImageLaunchedShouldKillIt
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.
```

**Expected behavior**
Kill command succeeds.

**Screenshots**

**Version information:**
 - OS: x86_64 GNU/Linux
 - Version: #42~20.04.1-Ubuntu

**Expected development cost**
Find a root cause of pthead_setschedparam() failure...

**Comment by demarey** [comment]
@Bajger The pthead_setschedparam()  is not a failure but a warning. It happens because the VM is run with a user not allowed to change the priority. You can see these warnings in the UI Pharo Launcher tests too.
The only problem is the return code that is not zero.

**Comment by Bajger** [comment]
Hi! Yes, I was seeking this answer on discord and realized problem is not in this warning (it took me a while). I realized process list command works differently on Linux and then identification (grepping) of PID is wrongly identified from the line of process information. I will seek and fix this (that's why probably even kill command doesn't work fully ok).
