### ISSUE TITLE
Merge David's work and architecture with the functional commands

### ISSUE THREAD

**Issue by axlgithub** [axlgithub/CommandLineLauncher#5]

**Comment by Bajger** [comment]
@axlgithub Hi Alex! Do you have details where I can take a look? Or is it already in dev-branch?

**Comment by demarey** [comment]
@Bajger you can take a look at the [merge-david-axel branch](/axlgithub/CommandLineLauncher/tree/merge-david-axel).

**Comment by Bajger** [comment]
I did a review with some general proposal. In addition I propose to add some new tickets for error/exception handling, how to access and verify parameters, how to use formatter.

**Comment by demarey** [comment]
done in #11
